### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by LoneStar-** [kpsuperplane/OnePlus-Sidebar-Script#74]
Ok, after the last update, the side bar works in firefox, great job. Now the only issue I see, is the rainbow text effect is nowhere to be seen. Just a small issue, just letting you know.

**Comment by JuanPotato** [comment]
I've seen this and am trying to fix it. -_- firefox is just stupid sometimes.

**Comment by JuanPotato** [comment]
FIREFOX FIXED
SPEEAD THE WORD
