### ISSUE TITLE
View All issue

### ISSUE THREAD

**Issue by Tamashi** [kpsuperplane/OnePlus-Sidebar-Script#77]
The "View All" link seems to be broken or malfunctioning. When it's pressed, it doesn't actually take me to the categories, but refreshes the page, rather.

I'm using Chrome on my PC. Windows 8.1 64-bit.

**Comment by JuanPotato** [comment]
Can you get a video of this happening? I'm not getting this bug :|

**Comment by Tamashi** [comment]
It magically resolved itself. Guess it was a caching issue. Will report in a PM on the forum if it happens again.
