### ISSUE TITLE
Quick PM issue

### ISSUE THREAD

**Issue by Tamashi** [kpsuperplane/OnePlus-Sidebar-Script#78]
Hey guys,

As a mod on the forum, I always send out private messages to the original poster of the thread I'm locking or taking action to. The "Quick PM" feature is really useful, but something bothers me a lot about it. It seems to not respect enters or white space. When you type something, it appears all as one block of text, making it look quite unprofessional.

Any chance to update this to respect enters/line breaks?

**Comment by JuanPotato** [comment]
working on it

**Comment by JuanPotato** [comment]
Done :3
Please update
